import { useEffect, useState } from "react";
import { doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { BarChart3, CheckCircle2, MapPin, MessageCircle, Plus, Search, Trash2 } from "lucide-react";
import { db } from "../firebaseConfig";
import { PUBLIC_INTEGRATION_DEFAULTS } from "../lib/integrationDefaults";

const defaultLocations = [
  { id:"plaza-carolina",city:"San Pedro Sula",name:"Plaza Carolina",detail:"Segundo nivel, bulevar Mackay",phone:"50493385732",maps:"https://www.google.com/maps/search/?api=1&query=TECPOINT%20Plaza%20Carolina%20San%20Pedro%20Sula" },
  { id:"portal-viera",city:"Tegucigalpa",name:"Portal de Viera",detail:"Tercer nivel, km 3 carretera a El Hatillo",phone:"50495200523",maps:"https://www.google.com/maps/search/?api=1&query=TECPOINT%20Portal%20de%20Viera%20Tegucigalpa" },
  { id:"mayoreo-pickup",city:"San Pedro Sula",name:"Mayoreo y Pick Up",detail:"Barrio Los Andes, 7 calle, 14 avenida",phone:"50498191003",maps:"https://www.google.com/maps/search/?api=1&query=TECPOINT%20Barrio%20Los%20Andes%207%20Calle%2014%20Avenida%20San%20Pedro%20Sula" },
];
const defaults = { mainWhatsApp:"50497157784",onlineWhatsApp:"50494659287",wholesaleWhatsApp:"50498191003",...PUBLIC_INTEGRATION_DEFAULTS,locations:defaultLocations };

export default function SiteSettings() {
  const [data,setData] = useState(defaults); const [saving,setSaving] = useState(false); const [saved,setSaved] = useState(false); const [error,setError] = useState("");
  useEffect(()=>{getDoc(doc(db,"site_settings","general")).then(s=>s.exists()&&setData({...defaults,...s.data(),locations:s.data().locations?.length?s.data().locations:defaultLocations})).catch(()=>setError("No fue posible cargar la configuración actual."));},[]);
  const update=(key,value)=>setData(prev=>({...prev,[key]:value}));
  const updateLocation=(index,key,value)=>update("locations",data.locations.map((location,i)=>i===index?{...location,[key]:value}:location));
  const save=async(e)=>{e.preventDefault();setSaving(true);setSaved(false);setError("");try{
    const phones=[data.mainWhatsApp,data.onlineWhatsApp,data.wholesaleWhatsApp,...data.locations.map(location=>location.phone)].map(value=>String(value||"").replace(/\D/g,""));
    if(phones.some(phone=>phone.length<11||phone.length>15)) throw new Error("Revise los números de WhatsApp e incluya el código de país 504.");
    if(data.metaPixelId&&!/^\d{8,20}$/.test(String(data.metaPixelId).trim())) throw new Error("El ID de Meta Pixel debe contener únicamente números.");
    if(data.gaMeasurementId&&!/^G-[A-Z0-9]+$/i.test(String(data.gaMeasurementId).trim())) throw new Error("El ID de Google Analytics debe comenzar con G-.");
    if(!data.locations.length) throw new Error("Debe conservar al menos una ubicación.");
    if(data.locations.some(location=>!location.name.trim()||!location.city.trim()||!location.detail.trim()||!/^https:\/\//i.test(location.maps))) throw new Error("Complete nombre, ciudad, dirección y enlace https:// de Google Maps en cada ubicación.");
    const normalized={...data,mainWhatsApp:phones[0],onlineWhatsApp:phones[1],wholesaleWhatsApp:phones[2],locations:data.locations.map((location,index)=>({...location,phone:phones[index+3]})),updatedAt:serverTimestamp()};
    await setDoc(doc(db,"site_settings","general"),normalized,{merge:true});setData(previous=>({...previous,...normalized,updatedAt:previous.updatedAt}));setSaved(true);
  }catch(caught){setError(caught.message||"No fue posible guardar la configuración.");}finally{setSaving(false)}};
  return <form onSubmit={save} className="space-y-7">
    <header><p className="text-xs font-bold tracking-[.2em] text-red-600">CONFIGURACIÓN CENTRAL</p><h1 className="text-3xl font-bold">Integraciones, WhatsApp y ubicaciones</h1><p className="mt-2 max-w-3xl text-gray-600">Los cambios guardados se aplican en navegación, carrito, fichas, pie de página y puntos de atención sin editar el código.</p></header>
    {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
    <section className="grid gap-4 lg:grid-cols-3">
      <StatusCard icon={BarChart3} title="Meta Pixel" active={Boolean(data.metaPixelId)} text={data.metaPixelId || "Falta configurar el ID"} href="https://business.facebook.com/events_manager2" />
      <StatusCard icon={BarChart3} title="Google Analytics 4" active={Boolean(data.gaMeasurementId)} text={data.gaMeasurementId || "Falta configurar el Measurement ID"} href="https://analytics.google.com/" />
      <StatusCard icon={Search} title="Google Search Console" active={Boolean(data.searchConsoleProperty)} text={data.searchConsoleProperty || "Propiedad sin configurar"} href="https://search.google.com/search-console" />
    </section>
    <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Integraciones de medición</h2><p className="mb-5 text-sm text-gray-500">Use los identificadores oficiales. Guardarlos no crea las cuentas; conecta la web con cuentas ya existentes.</p><div className="grid gap-4 md:grid-cols-2"><Field label="Meta Pixel ID" value={data.metaPixelId} onChange={v=>update("metaPixelId",v)} placeholder="Ej. 123456789012345"/><Field label="Google Analytics Measurement ID" value={data.gaMeasurementId} onChange={v=>update("gaMeasurementId",v)} placeholder="G-XXXXXXXXXX"/><Field label="Token de verificación Search Console" value={data.googleSiteVerification} onChange={v=>update("googleSiteVerification",v)} /><Field label="Propiedad de Search Console" value={data.searchConsoleProperty} onChange={v=>update("searchConsoleProperty",v)} placeholder="https://tecpoint.ws/"/></div></section>
    <section className="rounded-2xl border bg-white p-6"><div className="flex items-center gap-3"><MessageCircle className="text-red-600"/><h2 className="text-xl font-bold">Números de WhatsApp</h2></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Field label="Pedidos principales" value={data.mainWhatsApp} onChange={v=>update("mainWhatsApp",v)} /><Field label="Tienda en línea" value={data.onlineWhatsApp} onChange={v=>update("onlineWhatsApp",v)} /><Field label="Mayoreo" value={data.wholesaleWhatsApp} onChange={v=>update("wholesaleWhatsApp",v)} /></div><p className="mt-3 text-xs text-gray-500">Incluya código de país: Honduras 504. El sistema elimina espacios y guiones al crear el enlace.</p></section>
    <section className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><MapPin className="text-red-600"/><div><h2 className="text-xl font-bold">Ubicaciones y puntos de atención</h2><p className="text-sm text-gray-500">Actualice ciudad, dirección, teléfono y enlace exacto de Google Maps.</p></div></div><button type="button" onClick={()=>update("locations",[...data.locations,{id:`location-${Date.now()}`,city:"",name:"Nueva ubicación",detail:"",phone:data.mainWhatsApp,maps:""}])} className="flex items-center gap-2 rounded-lg border px-4 py-2 font-bold"><Plus size={17}/> Agregar</button></div><div className="mt-5 space-y-4">{data.locations.map((location,index)=><div key={location.id} className="grid gap-3 rounded-xl bg-gray-50 p-4 md:grid-cols-2 xl:grid-cols-6"><Field label="Nombre" value={location.name} onChange={v=>updateLocation(index,"name",v)}/><Field label="Ciudad" value={location.city} onChange={v=>updateLocation(index,"city",v)}/><Field label="Dirección" value={location.detail} onChange={v=>updateLocation(index,"detail",v)} className="xl:col-span-2"/><Field label="WhatsApp" value={location.phone} onChange={v=>updateLocation(index,"phone",v)}/><div className="flex items-end gap-2"><Field label="Google Maps" value={location.maps} onChange={v=>updateLocation(index,"maps",v)}/><button type="button" aria-label="Eliminar ubicación" onClick={()=>update("locations",data.locations.filter((_,i)=>i!==index))} className="mb-1 rounded-lg border border-red-200 p-3 text-red-700"><Trash2 size={18}/></button></div></div>)}</div></section>
    <div className="sticky bottom-4 flex justify-end"><button disabled={saving} className="rounded-xl bg-[#cf1533] px-8 py-4 font-bold text-white shadow-xl disabled:opacity-50">{saving?"Guardando…":saved?"Cambios guardados ✓":"Guardar configuración"}</button></div>
  </form>;
}
 
function Field({label,value,onChange,className="",...props}){return <label className={`block text-sm font-semibold ${className}`}>{label}<input value={value||""} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-3 font-normal" {...props}/></label>}
 
function StatusCard({icon:Icon,title,active,text,href}){return <article className="rounded-2xl border bg-white p-5"><div className="flex items-start justify-between"><span className="rounded-xl bg-gray-100 p-3"><Icon/></span><span className={`flex items-center gap-1 rounded-full px-3 py-1 text-xs font-bold ${active?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{active&&<CheckCircle2 size={13}/>} {active?"Configurado":"Pendiente"}</span></div><h2 className="mt-5 text-xl font-bold">{title}</h2><p className="mt-1 break-all text-sm text-gray-500">{text}</p><a href={href} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-red-700">Abrir plataforma →</a></article>}
